-- seeds/01_users.sql
-- Insert 50 users (mix of active / inactive / blocked)

INSERT INTO users (email, full_name, status, created_at) VALUES
('ana.lopez@example.com', 'Ana López', 'active', NOW() - INTERVAL '120 days'),
('carlos.ramirez@example.com', 'Carlos Ramírez', 'active', NOW() - INTERVAL '118 days'),
('maria.hernandez@example.com', 'María Hernández', 'active', NOW() - INTERVAL '116 days'),
('jose.garcia@example.com', 'José García', 'active', NOW() - INTERVAL '114 days'),
('laura.torres@example.com', 'Laura Torres', 'active', NOW() - INTERVAL '112 days'),
('diego.martinez@example.com', 'Diego Martínez', 'active', NOW() - INTERVAL '110 days'),
('sofia.vargas@example.com', 'Sofía Vargas', 'active', NOW() - INTERVAL '108 days'),
('luis.flores@example.com', 'Luis Flores', 'active', NOW() - INTERVAL '106 days'),
('paola.sanchez@example.com', 'Paola Sánchez', 'active', NOW() - INTERVAL '104 days'),
('fernando.rojas@example.com', 'Fernando Rojas', 'active', NOW() - INTERVAL '102 days'),

('valeria.castillo@example.com', 'Valeria Castillo', 'active', NOW() - INTERVAL '100 days'),
('ricardo.navarro@example.com', 'Ricardo Navarro', 'active', NOW() - INTERVAL '98 days'),
('daniela.ortiz@example.com', 'Daniela Ortiz', 'active', NOW() - INTERVAL '96 days'),
('miguel.mendoza@example.com', 'Miguel Mendoza', 'active', NOW() - INTERVAL '94 days'),
('karla.gomez@example.com', 'Karla Gómez', 'active', NOW() - INTERVAL '92 days'),
('andres.silva@example.com', 'Andrés Silva', 'active', NOW() - INTERVAL '90 days'),
('monica.pena@example.com', 'Mónica Peña', 'active', NOW() - INTERVAL '88 days'),
('jorge.ruiz@example.com', 'Jorge Ruiz', 'active', NOW() - INTERVAL '86 days'),
('ximena.castro@example.com', 'Ximena Castro', 'active', NOW() - INTERVAL '84 days'),
('pablo.reyes@example.com', 'Pablo Reyes', 'active', NOW() - INTERVAL '82 days'),

('isabel.morales@example.com', 'Isabel Morales', 'active', NOW() - INTERVAL '80 days'),
('eduardo.herrera@example.com', 'Eduardo Herrera', 'active', NOW() - INTERVAL '78 days'),
('camila.romero@example.com', 'Camila Romero', 'active', NOW() - INTERVAL '76 days'),
('oscar.rivera@example.com', 'Óscar Rivera', 'active', NOW() - INTERVAL '74 days'),
('alejandra.nunez@example.com', 'Alejandra Núñez', 'active', NOW() - INTERVAL '72 days'),
('hector.salazar@example.com', 'Héctor Salazar', 'active', NOW() - INTERVAL '70 days'),
('gabriela.molina@example.com', 'Gabriela Molina', 'active', NOW() - INTERVAL '68 days'),
('roberto.delgado@example.com', 'Roberto Delgado', 'active', NOW() - INTERVAL '66 days'),
('lucia.ramos@example.com', 'Lucía Ramos', 'active', NOW() - INTERVAL '64 days'),
('sergio.ponce@example.com', 'Sergio Ponce', 'active', NOW() - INTERVAL '62 days'),

('adriana.estrada@example.com', 'Adriana Estrada', 'active', NOW() - INTERVAL '60 days'),
('marco.ibarra@example.com', 'Marco Ibarra', 'active', NOW() - INTERVAL '58 days'),
('renata.cervantes@example.com', 'Renata Cervantes', 'active', NOW() - INTERVAL '56 days'),
('raul.guerrero@example.com', 'Raúl Guerrero', 'active', NOW() - INTERVAL '54 days'),
('julieta.aguilar@example.com', 'Julieta Aguilar', 'active', NOW() - INTERVAL '52 days'),
('ivan.arias@example.com', 'Iván Arias', 'active', NOW() - INTERVAL '50 days'),
('paulinaa.mejia@example.com', 'Paulina Mejía', 'active', NOW() - INTERVAL '48 days'),
('tomas.soto@example.com', 'Tomás Soto', 'active', NOW() - INTERVAL '46 days'),

('brenda.valdez@example.com', 'Brenda Valdez', 'inactive', NOW() - INTERVAL '44 days'),
('cesar.luna@example.com', 'César Luna', 'inactive', NOW() - INTERVAL '43 days'),
('mariana.vega@example.com', 'Mariana Vega', 'inactive', NOW() - INTERVAL '42 days'),
('kevin.fuentes@example.com', 'Kevin Fuentes', 'inactive', NOW() - INTERVAL '41 days'),
('diana.carrillo@example.com', 'Diana Carrillo', 'inactive', NOW() - INTERVAL '40 days'),
('sebastian.campos@example.com', 'Sebastián Campos', 'inactive', NOW() - INTERVAL '39 days'),
('fatima.escobar@example.com', 'Fátima Escobar', 'inactive', NOW() - INTERVAL '38 days'),

('hugo.cortes@example.com', 'Hugo Cortés', 'blocked', NOW() - INTERVAL '20 days'),
('veronica.medina@example.com', 'Verónica Medina', 'blocked', NOW() - INTERVAL '18 days'),
('samuel.pacheco@example.com', 'Samuel Pacheco', 'blocked', NOW() - INTERVAL '16 days'),
('natalia.miranda@example.com', 'Natalia Miranda', 'blocked', NOW() - INTERVAL '14 days'),
('cristian.bautista@example.com', 'Cristian Bautista', 'blocked', NOW() - INTERVAL '12 days');
